# Generated by Django 3.2.19 on 2025-02-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20250211_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Screen',
        ),
    ]
