# Generated by Django 3.2.19 on 2025-02-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_delete_screen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='theater',
        ),
    ]
