# Generated by Django 3.2.19 on 2025-02-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movieintheater'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieInTheater',
        ),
    ]
