# Generated by Django 3.2.19 on 2025-02-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_delete_movieintheater'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi')], default='Action', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Spanish', 'Spanish'), ('French', 'French')], default='English', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
