# Generated by Django 3.2.19 on 2025-02-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20250220_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='show',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='theater',
            unique_together=set(),
        ),
    ]
